### ISSUE TITLE
llvm version >= 3.5 support

### ISSUE THREAD

**Issue by dana** [davidgiven/calculon#4]
I'm on Ubuntu 16, which seems to only ship with llvm-3.5 - llvm-3.7.

I would LOVE to play around with this (and the related Flooded Moon project).

Thank you for your consideration.

**Comment by davidgiven** [comment]
Wow, LLVM has moved on since I last touched this.

I'll look at upgrading it; but it doesn't seem to be trivial, unfortunately. No promises on timescale.

**Comment by davidgiven** [comment]
Done; it's fairly crudely updated to work with LLVM 3.7 --- it really needs a proper C++11 conversion, but the tests pass. I can't comment on whether the performance has changed or not.

Let me know how you get on...
